# 5.16 List 2 Dimensi

List 2 dimensi pada umumnya adalah menempatkan sebuah list di dalam list. List 2 Dimensi biasanya menyimpan data yang kompleks seperti maktriks.

In [13]:
matrix = [[ 1, 2, 3, 4],
          [ 5, 6, 7, 8],
          [ 9,10,11,12],
          [13,14,15,16]]
print("Matriks yang kita miliki adalah :")
print (matrix)

# List 2 Dimensi terlihat seperti ada list di dalam list.
# INGAT!! Indeks selalu dimulai dari 0
#  - berarti dari matriks diatas terdapat kolom 0, kolom 1, sampai kolom 4
#  - dari matriks diatas terdapat baris 0, baris 1, sampai baris 4

#Cara menampilkan data pada List 2 Dimensi bisa menggunakan perulangan atau menunjukkan indeksnya

###### Menampilkan data dengan menunjukkan indeksnya ######
# Contoh, saya ingin mencetak data 12, data 12 terletak pada baris ketiga dan kolom keempat
# Karena indeks dimulai dari nol, maka data 12 terletak pada indeks 2 dan 3
# Kita bisa menampilkan dengan cara :
print("\nElemen yang terletak di baris ke-3 dan kolom ke-4 yaitu :")
print(matrix [2][3])

# Kita juga bisa membuatnya tanpa kata "PRINT"
# Kurung siku pertama menandakan indeks untuk baris dan kurung siku kedua menandakan indeks untuk kolom

# Contoh lain, saya ingin mencetak semua data yang ada pada baris keempat
# Karena indeks dimulai dari nol, maka baris keempat memiliki indeks 3
# Kita bisa menampilkan dengan cara :
print("\nElemen yang terletak di baris ke-4 yaitu :")
print(matrix [3])

# Kita juga bisa membuatnya tanpa kata "PRINT"
# Hanya terdapat 1 kurung siku yang menandakan indeks tersebut untuk baris

###### Menampilkan data dengan menunjukkan jangkauan indeksnya ######
# Contoh, saya ingin mencetak data baris kedua dan ketiga
# Karena indeks dimulai dari nol, maka baris jangkauan barisnya terletak pada 1-3 dengan indeks 3 tidak termasuk
# Kita bisa menampilkan dengan cara :
print("\nElemen yang terletak di baris ke-2 dan ke-3 yaitu :")
print(matrix [1:3])

###### Mencetak data Matriks dengan rapi ######
# Kita dapat mencetak data matriks dengan rapi menggunakan perulangan for
# Posisi entri-entrinya tidak akan mendatar untuk semuanya, namun akan tercetak sama seperti bentuk matriks yang biasa kita lihat
print("\nBerikut Matriks yang rapi dengan menggunakan perulangan for :")
matriksId = [[ 1,0],
             [0,1]]
for baris in matriksId:
    print(baris)
print("\nBerikut contoh lainnya:")
for baris in matrix:
    print(baris)
#Saya masih belum tau caranya agar matriks terlihat lebih rapi, karena elemen-elemennya mengandung jumlah digit karakter yang berbeda

Matriks yang kita miliki adalah :
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

Elemen yang terletak di baris ke-3 dan kolom ke-4 yaitu :
12

Elemen yang terletak di baris ke-4 yaitu :
[13, 14, 15, 16]

Elemen yang terletak di baris ke-2 dan ke-3 yaitu :
[[5, 6, 7, 8], [9, 10, 11, 12]]

Berikut Matriks yang rapi dengan menggunakan perulangan for :
[1, 0]
[0, 1]

Berikut contoh lainnya:
[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]


In [20]:
###### Menampilkan data dengan perulangan menunjuk indeksnya ######
print("Berikut matriks yang memiliki jumlah digit karakter berbeda :")
for i in range(4):                       #perulangan pertama menunjukkan baris yaitu ada 4 baris
    for j in range (4):                  #perulangan kedua menunjukkan kolom yaitu ada 4 kolom
        print(matrix[i][j], end=' ')     #agar data yang tercetak terlihat seperti matriks, tambahkan (end=' ')
    print()                              #dan ketika perulangan j selesai, kita tambahkan enter dengan "print()"
    
#Saya masih belum tau caranya agar matriks ini terlihat lebih rapi, karena elemen-elemennya mengandung jumlah digit karakter yang berbeda
print()

#Contoh matriks lainnya
print("Berikut matriks yang memiliki 1 digit karakter :")
matriks1 =[[1,2,3,4],
          [2,4,6,8],
          [3,5,7,9]]
for i in range(3):                         #perulangan pertama menunjukkan baris yaitu ada 3 baris
    for j in range (3):                    #perulangan kedua menunjukkan kolom yaitu ada 3 kolom
        print(matriks1[i][j], end=' ')     #agar data yang tercetak terlihat seperti matriks, tambahkan (end=' ')
    print()                                #dan ketika perulangan j selesai, kita tambahkan enter dengan "print()"
    
print()
print("Berikut matriks yang memiliki 2 digit karakter :")
matriks2 =[[12,13],
          [14,15]]
for i in range(2):                         #perulangan pertama menunjukkan baris yaitu ada 2 baris
    for j in range (2):                    #perulangan kedua menunjukkan kolom yaitu ada 2 kolom
        print(matriks2[i][j], end=' ')     #agar data yang tercetak terlihat seperti matriks, tambahkan (end=' ')
    print()                                #dan ketika perulangan j selesai, kita tambahkan enter dengan "print()"
    
    

Berikut matriks yang memiliki jumlah digit karakter berbeda :
1 2 3 4 
5 6 7 8 
9 10 11 12 
13 14 15 16 

Berikut matriks yang memiliki 1 digit karakter :
1 2 3 
2 4 6 
3 5 7 

Berikut matriks yang memiliki 2 digit karakter :
12 13 
14 15 


In [54]:
###### Menampilkan data dengan perulangan tanpa menunjuk indeksnya ######
print("Berikut hasil matriks dengan perulangan tanpa menunjuk indeksnya :")
for i in matrix:               #kita akan mengakses data pada variabel matrix, i akan menunjukkan elemen pada setiap baris
    for j in i:                #j akan menunjukkan setiap elemen pada kolom
        print(j, end=' ')      #agar data yang tercetak terlihat seperti matriks, tambahkan (end=' ')
    print()                    #dan ketika perulangan j selesai, kita tambahkan enter dengan "print()"

print()

#Contoh lain
print("Berikut contoh lainnya :")
for i in matriks1:             #kita akan mengakses data pada variabel matrix, i akan menunjukkan elemen pada setiap baris
    for j in i:                #j akan menunjukkan setiap elemen pada kolom
        print(j, end=' ')      #agar data yang tercetak terlihat seperti matriks, tambahkan (end=' ')
    print()                    #dan ketika perulangan j selesai, kita tambahkan enter dengan "print()"

Berikut hasil matriks dengan perulangan tanpa menunjuk indeksnya :
1 2 3 4 
5 6 7 8 
9 10 11 12 
13 14 15 16 

Berikut contoh lainnya :
1 2 3 4 
2 4 6 8 
3 5 7 9 


In [117]:
# Kita juga bisa menggabungkan list-list yang kita miliki
data1 = [0,1]
data2 = [2,3]
listdataBiasa = [0,1,2,3]
listGabungan = [data1,data2]
print("Berikut output list data dengan biasa :", listdataBiasa)
print("Berikut output menggabungan list yang berbeda :", listGabungan)

Berikut output list data dengan biasa : [0, 1, 2, 3]
Berikut output menggabungan list yang berbeda : [[0, 1], [2, 3]]


###### Contoh (1) 

In [85]:
# Kita memiliki data biodata mahasiswa Prodi Matematika Angkatan 2022
mhs1 = ['Dudung',18,'Perempuan']
mhs2 = ['Ucup',20,'Laki-laki']
mhs3 = ['Bunga',19,'Perempuan']
mhs4 = ['Gaia',19,'Perempuan']
mhs5 = ['Axel',20,'Laki-laki']

listMhs = [mhs1,mhs2,mhs3,mhs4,mhs5]
print("Berikut merupakan biodata mahasiswa Prodi Matematika Angkatan 2022 :")
for mhs in listMhs:
    print("Nama          :", mhs[0])
    print('Umur          :', mhs[1])
    print('Jenis Kelamin :', mhs[2])
    print()

Berikut merupakan biodata mahasiswa Prodi Matematika Angkatan 2022 :
Nama          : Dudung
Umur          : 18
Jenis Kelamin : Perempuan

Nama          : Ucup
Umur          : 20
Jenis Kelamin : Laki-laki

Nama          : Bunga
Umur          : 19
Jenis Kelamin : Perempuan

Nama          : Gaia
Umur          : 19
Jenis Kelamin : Perempuan

Nama          : Axel
Umur          : 20
Jenis Kelamin : Laki-laki



###### Contoh (2) 

In [86]:
# Program List Buku Perpustakaan
listBuku = []                                                     #list kosong sebagai penampung list yang baru diinput
while True:                                                       #gunakan perulangan while agar perulangan diolah sampai kita cancel 
    print('Masukkan data buku')
    judul = input('Judul buku\t: ')
    penulis = input('Nama penulis\t: ')
    buku = [judul,penulis]                                        #menggabungkan list yang kita miliki
    listBuku.append(buku)                                         #fungsi append untuk menambahkan list baru pada list kosong
    
    print('\n','='*20,'Data Buku Perpustakaan','='*20)
    print('No.','|','Judul\t\t\t','|','Penulis' )                 # '\t' memiliki fungsi sebagai tab, untuk merapikan indentasi output   
    for index,kumBuku in enumerate(listBuku):                     #gunakan looping untuk print buku, enumerate digunakan agar kita mengetahui indexnya
        print(index+1,' ','|',kumBuku[0],'\t\t','|',kumBuku[1])   #indeks pada python selalu dimulai dari nol, maka kita tambahkan 1 agar nomor dapat dimulai dari 1
    
    print('\n','='*66)
    lanjut = input('Apakah ingin menginput lagi? (y/n)')          #karena while tidak akan berhenti tanpa ada cancel,
    if lanjut == 'n':                                             #maka kita buatkan looping for untuk menyelesaikan input ketika input ingin diselesaikan
        break                                                     #break digunakan untuk menghentikan perulangan
        
print("-Terima Kasih-")

Masukkan data buku
Judul buku	: Rentang Kisah
Nama penulis	: Gita Savitri Devi

 ==================== Data Buku Perpustakaan ====================
No. | Judul			 | Penulis
1   | Rentang Kisah 		 | Gita Savitri Devi

Apakah ingin menginput lagi? (y/n)y
Masukkan data buku
Judul buku	: Masih Belajar
Nama penulis	: Iman Usman

 ==================== Data Buku Perpustakaan ====================
No. | Judul			 | Penulis
1   | Rentang Kisah 		 | Gita Savitri Devi
2   | Masih Belajar 		 | Iman Usman

Apakah ingin menginput lagi? (y/n)n
-Terima Kasih-


# 5.17 Tuples

Tuple merupakan collection data type, artinya tuple dapat digunakan untuk menampung sekumpulan nilai/data.
Tuple merupakan sequence data type, artinya nilai/data yang tersimpan di dalam tuple dapat diakses berdasarkan urutan penyimpanannya. Dalam hal ini kita dapat memanfaatkan index.
Tuple merupakan immutable data type, artinya kita tidak dapat mengubah, menambah, ataupun menghapus nilai/data yang ditampung di dalam sebuah tuple.

In [92]:
print("Pendefinisian variabel dengan mengapit kumpulan data menggunakan tanda kurung :")
angka = (0,1,1,3,4,5)
print(angka)
print("\nPendefinisian variabel tanpa mengapit kumpulan data menggunakan tanda kurung :")
angka = 0,1,1,3,4,5
print(angka)
# Suatu Tuples tidak harus didefinisikan dengan mengapit kumpulan data dengan tanda kurung
# Output yang tercetak juga tetap Tuple

# Bagaimana jika suatu Tuple hanya memiliki 1 elemen?
# agar definisi Tuple tidak terindentifikasi sebagai int, 
# data Tuple dapat didefinisikan sebagai berikut
print("\nPendefinisian variabel yang hanya memiliki satu elemen :")
satuE = 15,
print(satuE)

# Tuple juga dapat menampung sekumpulan nilai dengan tipe data yang bervariasi
print("\nTuple dapat menampung sekumpulan nilai dengan tipe data yang bervariasi :")
tuple1 = (2,5,3.3,'deswinta',5,2,['x','y'],True,1,5,2.3,3.3,2 )
print(tuple1)
# Dapat dilihat tuple1 dapat menampung nilai-nilai dengan tipe data yang beragam
# Seperti contoh di atas terdapat tipe data int, float, string, list dan boolean 
# di dalam suatu tuple kita juga dapat menyimpan list dan suatu tuple lainnya

# Untuk menghitung frekuensi nilai yang kita miliki dalam Tuple
# kita dapat menggunakan fungsi count
print("\nBerikut frekuensi nilai 2 pada Tuple1 :", tuple1.count(2))

# Untuk mengetahui urutan nilai dalam Tuple
# kita dapat menggunakan fungsi index
print("\nBerikut letak 'deswinta' pada Tuple1 :", tuple1.index('deswinta'))

Pendefinisian variabel dengan mengapit kumpulan data menggunakan tanda kurung :
(0, 1, 1, 3, 4, 5)

Pendefinisian variabel tanpa mengapit kumpulan data menggunakan tanda kurung :
(0, 1, 1, 3, 4, 5)

Pendefinisian variabel yang hanya memiliki satu elemen :
(15,)

Tuple dapat menampung sekumpulan nilai dengan tipe data yang bervariasi :
(2, 5, 3.3, 'deswinta', 5, 2, ['x', 'y'], True, 1, 5, 2.3, 3.3, 2)

Berikut frekuensi nilai 2 pada Tuple1 : 3

Berikut letak 'deswinta' pada Tuple1 : 3


# 5.18 Dictionaries

##### Dictionary

In [12]:
# Dictionary (dict) disebut associative array. 
# Kita mengakses datanya sebagai identifier, tidak seperti data list yang menggunakan indeks
# Contoh
dataList = ['ibu','ayah','adik']
dataNama={
    'key': 'value',
    'ds' : 'Deswinta',
    'st' : 'Sinta',
    'no' : 11,
    'list' : dataList,     #kita juga dapat mengisi data list pada dictionary
}
print('Berikut adalah bentuk dari dictionary kita :')
print(dataNama) 

print('Berikut adalah data yang terpanggil dari "st" :')
print(dataNama['st'])       #kita tidak perlu menggunakan indeks dalam pemanggilan


Berikut adalah bentuk dari dictionary kita :
{'key': 'value', 'ds': 'Deswinta', 'st': 'Sinta', 'no': 11, 'list': ['ibu', 'ayah', 'adik']}
Berikut adalah data yang terpanggil dari "st" :
Sinta


##### Operasi Dictionary

In [32]:
dataDict = {
    'kupu' : 'kupu kupu',
    'kata' : 'kata kata',
    'tiba' : 'tiba tiba'
}

# panjang dictionary
lendict = len(dataDict)
print('Panjang dictionary adalah', lendict)

# mengecek apakah variabel ada atau tidak
key = 'kupu'                 #coba dengan elemen yang benar
checkkey = key in dataDict
print('Apakah', key, 'ada pada dictionary :', checkkey)
key = 'luou'
checkkey = key in dataDict   ##coba dengan elemen yang salah
print('Apakah', key, 'ada pada dictionary :', checkkey)
#output yang akan dimunculkan tipe data boolean, yaitu True or False

# mengakses/read nilai pada data dict dengan fungsi get
print('\nIni merupakan output dari fungsi get untuk mengakses nilai data pada dictionary :')
print(dataDict['kata'])      #jika kita menggunakan ini, kita sulit membedakan mana dict dan list
print(dataDict.get('kata'))  #dengan menggunakan get, kita bisa tau bahwa ini merupakan dictionary
print(dataDict.get('etp'))   #karena 'etp' bukan merupakan anggota dict, maka output yang dihasilkan yaitu 'None'
print(dataDict.get('etp', 'nilai tidak ditemukan'))   #karena 'etp' bukan anggota dict, kita bisa mengganti output 'None' menjadi pesan yang berbeda

# cara mengupdate dan menambah data pada dict
print('\nBerikut output saat mengupdate data :')
dataDict.update({'tiba' : 'tiba tiba cinta datang'})   #ketika variabel pada data dict sudah ada, maka fungsi akan mengganti nilainya
print(dataDict)
print('\nBerikut output saat menambah data :')
dataDict.update({'aku' : 'aku suka kwetiauw'})         #ketika variabel pada data dict belum ada, maka fungsi akan menambah data baru
print(dataDict)

Panjang dictionary adalah 3
Apakah kupu ada pada dictionary : True
Apakah luou ada pada dictionary : False

Ini merupakan output dari fungsi get untuk mengakses nilai data pada dictionary :
kata kata
kata kata
None
nilai tidak ditemukan

Berikut output saat mengupdate data :
{'kupu': 'kupu kupu', 'kata': 'kata kata', 'tiba': 'tiba tiba cinta datang'}

Berikut output saat menambah data :
{'kupu': 'kupu kupu', 'kata': 'kata kata', 'tiba': 'tiba tiba cinta datang', 'aku': 'aku suka kwetiauw'}


# 5.19 Fungsi dalam Python

In [92]:
# Fungsi di definisikan untu
def fungsi():                     #pendefinisian fungsi
    print('Ini adalah fungsi')    #tugas fungsi
fungsi()                          #pemanggilan fungsi harus setelah fungsi didefinisikan

Ini adalah fungsi


In [95]:
# Fungsi Nama Lengkap menerima input nama depan dan belakang
def fullName(firstName,lastName):                              #pendefisian fungsi
    print(f'\nNama lengkapnya adalah {firstName} {lastName}')
firstName = input("Nama depan anda adalah ")
lastName = input("Nama belakang anda adalah ")
fullName(firstName,lastName)

Nama depan anda adalah Putu
Nama belakang anda adalah Deswinta

Nama lengkapnya adalah Putu Deswinta


In [108]:
# Fungsi Waktu tempuh
def waktuTempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return waktu
    
waktuTempuh(80,60)

b = waktuTempuh(80,60)
print(b)

1.3333333333333333


In [ ]:
# Fungsi Luas Segitiga
def luasSegitiga(alas, tinggi):
    luas = 0.5*alas*tinggi
    return luas

# Fungsi Luas Lingkaran
def luaslingkaran(jari_jari):
    luas = 3.14*(jari_jari**2)
    return luas

# Fungsi Luas Persegi
def luaspeserta (jari_jari):
    luas = sisi**2
    return luas

# 5.20 Numpy

In [73]:
import numpy as np

In [74]:
a = np.array([0,1,2,3,4])
print(a)

[0 1 2 3 4]


In [79]:
b = np.array([[5,6,7,8],[9,8,7,6]])
print(b)

[[5 6 7 8]
 [9 8 7 6]]


In [94]:
c = np.array([[[0,1,2,3],[4,5,6,7]],
              [[8,9,8,7],[6,5,4,3]],
              [[1,2,3,4],[5,6,7,8]]])
print(c)

[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [92]:
b.ndim

2

In [95]:
c.ndim

3

In [96]:
c.shape

(3, 2, 4)