# 5.16 List 2 Dimensi

List 2 dimensi pada umumnya adalah menempatkan sebuah list di dalam list. List 2 Dimensi biasanya menyimpan data yang kompleks seperti maktriks.

In [13]:
matrix = [[ 1, 2, 3, 4],
          [ 5, 6, 7, 8],
          [ 9,10,11,12],
          [13,14,15,16]]
print("Matriks yang kita miliki adalah :")
print (matrix)

# List 2 Dimensi terlihat seperti ada list di dalam list.
# INGAT!! Indeks selalu dimulai dari 0
#  - berarti dari matriks diatas terdapat kolom 0, kolom 1, sampai kolom 4
#  - dari matriks diatas terdapat baris 0, baris 1, sampai baris 4

#Cara menampilkan data pada List 2 Dimensi bisa menggunakan perulangan atau menunjukkan indeksnya

###### Menampilkan data dengan menunjukkan indeksnya ######
# Contoh, saya ingin mencetak data 12, data 12 terletak pada baris ketiga dan kolom keempat
# Karena indeks dimulai dari nol, maka data 12 terletak pada indeks 2 dan 3
# Kita bisa menampilkan dengan cara :
print("\nElemen yang terletak di baris ke-3 dan kolom ke-4 yaitu :")
print(matrix [2][3])

# Kita juga bisa membuatnya tanpa kata "PRINT"
# Kurung siku pertama menandakan indeks untuk baris dan kurung siku kedua menandakan indeks untuk kolom

# Contoh lain, saya ingin mencetak semua data yang ada pada baris keempat
# Karena indeks dimulai dari nol, maka baris keempat memiliki indeks 3
# Kita bisa menampilkan dengan cara :
print("\nElemen yang terletak di baris ke-4 yaitu :")
print(matrix [3])

# Kita juga bisa membuatnya tanpa kata "PRINT"
# Hanya terdapat 1 kurung siku yang menandakan indeks tersebut untuk baris

###### Menampilkan data dengan menunjukkan jangkauan indeksnya ######
# Contoh, saya ingin mencetak data baris kedua dan ketiga
# Karena indeks dimulai dari nol, maka baris jangkauan barisnya terletak pada 1-3 dengan indeks 3 tidak termasuk
# Kita bisa menampilkan dengan cara :
print("\nElemen yang terletak di baris ke-2 dan ke-3 yaitu :")
print(matrix [1:3])

###### Mencetak data Matriks dengan rapi ######
# Kita dapat mencetak data matriks dengan rapi menggunakan perulangan for
# Posisi entri-entrinya tidak akan mendatar untuk semuanya, namun akan tercetak sama seperti bentuk matriks yang biasa kita lihat
print("\nBerikut Matriks yang rapi dengan menggunakan perulangan for :")
matriksId = [[ 1,0],
             [0,1]]
for baris in matriksId:
    print(baris)
print("\nBerikut contoh lainnya:")
for baris in matrix:
    print(baris)
#Saya masih belum tau caranya agar matriks terlihat lebih rapi, karena elemen-elemennya mengandung jumlah digit karakter yang berbeda

Matriks yang kita miliki adalah :
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

Elemen yang terletak di baris ke-3 dan kolom ke-4 yaitu :
12

Elemen yang terletak di baris ke-4 yaitu :
[13, 14, 15, 16]

Elemen yang terletak di baris ke-2 dan ke-3 yaitu :
[[5, 6, 7, 8], [9, 10, 11, 12]]

Berikut Matriks yang rapi dengan menggunakan perulangan for :
[1, 0]
[0, 1]

Berikut contoh lainnya:
[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]


In [20]:
###### Menampilkan data dengan perulangan menunjuk indeksnya ######
print("Berikut matriks yang memiliki jumlah digit karakter berbeda :")
for i in range(4):                       #perulangan pertama menunjukkan baris yaitu ada 4 baris
    for j in range (4):                  #perulangan kedua menunjukkan kolom yaitu ada 4 kolom
        print(matrix[i][j], end=' ')     #agar data yang tercetak terlihat seperti matriks, tambahkan (end=' ')
    print()                              #dan ketika perulangan j selesai, kita tambahkan enter dengan "print()"
    
#Saya masih belum tau caranya agar matriks ini terlihat lebih rapi, karena elemen-elemennya mengandung jumlah digit karakter yang berbeda
print()

#Contoh matriks lainnya
print("Berikut matriks yang memiliki 1 digit karakter :")
matriks1 =[[1,2,3,4],
          [2,4,6,8],
          [3,5,7,9]]
for i in range(3):                         #perulangan pertama menunjukkan baris yaitu ada 3 baris
    for j in range (3):                    #perulangan kedua menunjukkan kolom yaitu ada 3 kolom
        print(matriks1[i][j], end=' ')     #agar data yang tercetak terlihat seperti matriks, tambahkan (end=' ')
    print()                                #dan ketika perulangan j selesai, kita tambahkan enter dengan "print()"
    
print()
print("Berikut matriks yang memiliki 2 digit karakter :")
matriks2 =[[12,13],
          [14,15]]
for i in range(2):                         #perulangan pertama menunjukkan baris yaitu ada 2 baris
    for j in range (2):                    #perulangan kedua menunjukkan kolom yaitu ada 2 kolom
        print(matriks2[i][j], end=' ')     #agar data yang tercetak terlihat seperti matriks, tambahkan (end=' ')
    print()                                #dan ketika perulangan j selesai, kita tambahkan enter dengan "print()"
    
    

Berikut matriks yang memiliki jumlah digit karakter berbeda :
1 2 3 4 
5 6 7 8 
9 10 11 12 
13 14 15 16 

Berikut matriks yang memiliki 1 digit karakter :
1 2 3 
2 4 6 
3 5 7 

Berikut matriks yang memiliki 2 digit karakter :
12 13 
14 15 


In [54]:
###### Menampilkan data dengan perulangan tanpa menunjuk indeksnya ######
print("Berikut hasil matriks dengan perulangan tanpa menunjuk indeksnya :")
for i in matrix:               #kita akan mengakses data pada variabel matrix, i akan menunjukkan elemen pada setiap baris
    for j in i:                #j akan menunjukkan setiap elemen pada kolom
        print(j, end=' ')      #agar data yang tercetak terlihat seperti matriks, tambahkan (end=' ')
    print()                    #dan ketika perulangan j selesai, kita tambahkan enter dengan "print()"

print()

#Contoh lain
print("Berikut contoh lainnya :")
for i in matriks1:             #kita akan mengakses data pada variabel matrix, i akan menunjukkan elemen pada setiap baris
    for j in i:                #j akan menunjukkan setiap elemen pada kolom
        print(j, end=' ')      #agar data yang tercetak terlihat seperti matriks, tambahkan (end=' ')
    print()                    #dan ketika perulangan j selesai, kita tambahkan enter dengan "print()"

Berikut hasil matriks dengan perulangan tanpa menunjuk indeksnya :
1 2 3 4 
5 6 7 8 
9 10 11 12 
13 14 15 16 

Berikut contoh lainnya :
1 2 3 4 
2 4 6 8 
3 5 7 9 


In [117]:
# Kita juga bisa menggabungkan list-list yang kita miliki
data1 = [0,1]
data2 = [2,3]
listdataBiasa = [0,1,2,3]
listGabungan = [data1,data2]
print("Berikut output list data dengan biasa :", listdataBiasa)
print("Berikut output menggabungan list yang berbeda :", listGabungan)

Berikut output list data dengan biasa : [0, 1, 2, 3]
Berikut output menggabungan list yang berbeda : [[0, 1], [2, 3]]


###### Contoh (1) 

In [85]:
# Kita memiliki data biodata mahasiswa Prodi Matematika Angkatan 2022
mhs1 = ['Dudung',18,'Perempuan']
mhs2 = ['Ucup',20,'Laki-laki']
mhs3 = ['Bunga',19,'Perempuan']
mhs4 = ['Gaia',19,'Perempuan']
mhs5 = ['Axel',20,'Laki-laki']

listMhs = [mhs1,mhs2,mhs3,mhs4,mhs5]
print("Berikut merupakan biodata mahasiswa Prodi Matematika Angkatan 2022 :")
for mhs in listMhs:
    print("Nama          :", mhs[0])
    print('Umur          :', mhs[1])
    print('Jenis Kelamin :', mhs[2])
    print()

Berikut merupakan biodata mahasiswa Prodi Matematika Angkatan 2022 :
Nama          : Dudung
Umur          : 18
Jenis Kelamin : Perempuan

Nama          : Ucup
Umur          : 20
Jenis Kelamin : Laki-laki

Nama          : Bunga
Umur          : 19
Jenis Kelamin : Perempuan

Nama          : Gaia
Umur          : 19
Jenis Kelamin : Perempuan

Nama          : Axel
Umur          : 20
Jenis Kelamin : Laki-laki



###### Contoh (2) 

In [86]:
# Program List Buku Perpustakaan
listBuku = []                                                     #list kosong sebagai penampung list yang baru diinput
while True:                                                       #gunakan perulangan while agar perulangan diolah sampai kita cancel 
    print('Masukkan data buku')
    judul = input('Judul buku\t: ')
    penulis = input('Nama penulis\t: ')
    buku = [judul,penulis]                                        #menggabungkan list yang kita miliki
    listBuku.append(buku)                                         #fungsi append untuk menambahkan list baru pada list kosong
    
    print('\n','='*20,'Data Buku Perpustakaan','='*20)
    print('No.','|','Judul\t\t\t','|','Penulis' )                 # '\t' memiliki fungsi sebagai tab, untuk merapikan indentasi output   
    for index,kumBuku in enumerate(listBuku):                     #gunakan looping untuk print buku, enumerate digunakan agar kita mengetahui indexnya
        print(index+1,' ','|',kumBuku[0],'\t\t','|',kumBuku[1])   #indeks pada python selalu dimulai dari nol, maka kita tambahkan 1 agar nomor dapat dimulai dari 1
    
    print('\n','='*66)
    lanjut = input('Apakah ingin menginput lagi? (y/n)')          #karena while tidak akan berhenti tanpa ada cancel,
    if lanjut == 'n':                                             #maka kita buatkan looping for untuk menyelesaikan input ketika input ingin diselesaikan
        break                                                     #break digunakan untuk menghentikan perulangan
        
print("-Terima Kasih-")

Masukkan data buku
Judul buku	: Rentang Kisah
Nama penulis	: Gita Savitri Devi

 ==================== Data Buku Perpustakaan ====================
No. | Judul			 | Penulis
1   | Rentang Kisah 		 | Gita Savitri Devi

Apakah ingin menginput lagi? (y/n)y
Masukkan data buku
Judul buku	: Masih Belajar
Nama penulis	: Iman Usman

 ==================== Data Buku Perpustakaan ====================
No. | Judul			 | Penulis
1   | Rentang Kisah 		 | Gita Savitri Devi
2   | Masih Belajar 		 | Iman Usman

Apakah ingin menginput lagi? (y/n)n
-Terima Kasih-


# 5.17 Tuples

Tuple merupakan collection data type, artinya tuple dapat digunakan untuk menampung sekumpulan nilai/data.
Tuple merupakan sequence data type, artinya nilai/data yang tersimpan di dalam tuple dapat diakses berdasarkan urutan penyimpanannya. Dalam hal ini kita dapat memanfaatkan index.
Tuple merupakan immutable data type, artinya kita tidak dapat mengubah, menambah, ataupun menghapus nilai/data yang ditampung di dalam sebuah tuple.

In [92]:
print("Pendefinisian variabel dengan mengapit kumpulan data menggunakan tanda kurung :")
angka = (0,1,1,3,4,5)
print(angka)
print("\nPendefinisian variabel tanpa mengapit kumpulan data menggunakan tanda kurung :")
angka = 0,1,1,3,4,5
print(angka)
# Suatu Tuples tidak harus didefinisikan dengan mengapit kumpulan data dengan tanda kurung
# Output yang tercetak juga tetap Tuple

# Bagaimana jika suatu Tuple hanya memiliki 1 elemen?
# agar definisi Tuple tidak terindentifikasi sebagai int, 
# data Tuple dapat didefinisikan sebagai berikut
print("\nPendefinisian variabel yang hanya memiliki satu elemen :")
satuE = 15,
print(satuE)

# Tuple juga dapat menampung sekumpulan nilai dengan tipe data yang bervariasi
print("\nTuple dapat menampung sekumpulan nilai dengan tipe data yang bervariasi :")
tuple1 = (2,5,3.3,'deswinta',5,2,['x','y'],True,1,5,2.3,3.3,2 )
print(tuple1)
# Dapat dilihat tuple1 dapat menampung nilai-nilai dengan tipe data yang beragam
# Seperti contoh di atas terdapat tipe data int, float, string, list dan boolean 
# di dalam suatu tuple kita juga dapat menyimpan list dan suatu tuple lainnya

# Untuk menghitung frekuensi nilai yang kita miliki dalam Tuple
# kita dapat menggunakan fungsi count
print("\nBerikut frekuensi nilai 2 pada Tuple1 :", tuple1.count(2))

# Untuk mengetahui urutan nilai dalam Tuple
# kita dapat menggunakan fungsi index
print("\nBerikut letak 'deswinta' pada Tuple1 :", tuple1.index('deswinta'))

Pendefinisian variabel dengan mengapit kumpulan data menggunakan tanda kurung :
(0, 1, 1, 3, 4, 5)

Pendefinisian variabel tanpa mengapit kumpulan data menggunakan tanda kurung :
(0, 1, 1, 3, 4, 5)

Pendefinisian variabel yang hanya memiliki satu elemen :
(15,)

Tuple dapat menampung sekumpulan nilai dengan tipe data yang bervariasi :
(2, 5, 3.3, 'deswinta', 5, 2, ['x', 'y'], True, 1, 5, 2.3, 3.3, 2)

Berikut frekuensi nilai 2 pada Tuple1 : 3

Berikut letak 'deswinta' pada Tuple1 : 3


# 5.18 Dictionaries

##### Dictionary

In [12]:
# Dictionary (dict) disebut associative array. 
# Kita mengakses datanya sebagai identifier, tidak seperti data list yang menggunakan indeks
# Contoh
dataList = ['ibu','ayah','adik']
dataNama={
    'key': 'value',
    'ds' : 'Deswinta',
    'st' : 'Sinta',
    'no' : 11,
    'list' : dataList,     #kita juga dapat mengisi data list pada dictionary
}
print('Berikut adalah bentuk dari dictionary kita :')
print(dataNama) 

print('Berikut adalah data yang terpanggil dari "st" :')
print(dataNama['st'])       #kita tidak perlu menggunakan indeks dalam pemanggilan


Berikut adalah bentuk dari dictionary kita :
{'key': 'value', 'ds': 'Deswinta', 'st': 'Sinta', 'no': 11, 'list': ['ibu', 'ayah', 'adik']}
Berikut adalah data yang terpanggil dari "st" :
Sinta


##### Operasi Dictionary

In [32]:
dataDict = {
    'kupu' : 'kupu kupu',
    'kata' : 'kata kata',
    'tiba' : 'tiba tiba'
}

# panjang dictionary
lendict = len(dataDict)
print('Panjang dictionary adalah', lendict)

# mengecek apakah variabel ada atau tidak
key = 'kupu'                 #coba dengan elemen yang benar
checkkey = key in dataDict
print('Apakah', key, 'ada pada dictionary :', checkkey)
key = 'luou'
checkkey = key in dataDict   ##coba dengan elemen yang salah
print('Apakah', key, 'ada pada dictionary :', checkkey)
#output yang akan dimunculkan tipe data boolean, yaitu True or False

# mengakses/read nilai pada data dict dengan fungsi get
print('\nIni merupakan output dari fungsi get untuk mengakses nilai data pada dictionary :')
print(dataDict['kata'])      #jika kita menggunakan ini, kita sulit membedakan mana dict dan list
print(dataDict.get('kata'))  #dengan menggunakan get, kita bisa tau bahwa ini merupakan dictionary
print(dataDict.get('etp'))   #karena 'etp' bukan merupakan anggota dict, maka output yang dihasilkan yaitu 'None'
print(dataDict.get('etp', 'nilai tidak ditemukan'))   #karena 'etp' bukan anggota dict, kita bisa mengganti output 'None' menjadi pesan yang berbeda

# cara mengupdate dan menambah data pada dict
print('\nBerikut output saat mengupdate data :')
dataDict.update({'tiba' : 'tiba tiba cinta datang'})   #ketika variabel pada data dict sudah ada, maka fungsi akan mengganti nilainya
print(dataDict)
print('\nBerikut output saat menambah data :')
dataDict.update({'aku' : 'aku suka kwetiauw'})         #ketika variabel pada data dict belum ada, maka fungsi akan menambah data baru
print(dataDict)

Panjang dictionary adalah 3
Apakah kupu ada pada dictionary : True
Apakah luou ada pada dictionary : False

Ini merupakan output dari fungsi get untuk mengakses nilai data pada dictionary :
kata kata
kata kata
None
nilai tidak ditemukan

Berikut output saat mengupdate data :
{'kupu': 'kupu kupu', 'kata': 'kata kata', 'tiba': 'tiba tiba cinta datang'}

Berikut output saat menambah data :
{'kupu': 'kupu kupu', 'kata': 'kata kata', 'tiba': 'tiba tiba cinta datang', 'aku': 'aku suka kwetiauw'}


# 5.19 Fungsi dalam Python

In [165]:
# Fungsi di definisikan untuk meringkas kerja
def fungsi():                     #pendefinisian fungsi
    print('Ini adalah fungsi')    #tugas fungsi
fungsi()                          #pemanggilan fungsi harus setelah fungsi didefinisikan

Ini adalah fungsi


In [95]:
# Fungsi Nama Lengkap menerima input nama depan dan belakang
def fullName(firstName,lastName):                              #pendefisian fungsi
    print(f'\nNama lengkapnya adalah {firstName} {lastName}')
firstName = input("Nama depan anda adalah ")
lastName = input("Nama belakang anda adalah ")
fullName(firstName,lastName)

Nama depan anda adalah Putu
Nama belakang anda adalah Deswinta

Nama lengkapnya adalah Putu Deswinta


In [108]:
# Fungsi Waktu tempuh
def waktuTempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return waktu
    
waktuTempuh(80,60)

b = waktuTempuh(80,60)
print(b)

1.3333333333333333


In [112]:
# Fungsi Luas Segitiga
def luasSegitiga(alas, tinggi):
    luas = 0.5*alas*tinggi
    return luas

# Fungsi Luas Lingkaran
def luasLingkaran(jari_jari):
    luas = 3.14*(jari_jari**2)
    return luas

# Fungsi Luas Persegi
def luasPersegi (sisi):
    luas = sisi**2
    return luas

# Fungsi Luas Persegi Panjang
def luasPersegiPanjang (panjang, lebar):
    luas = panjang*lebar
    return luas

In [174]:
# Contoh Penggunaan dengan IF dan ELIF Statement
def header():
    print('Selamat datang pada program sederhana mencari Luas suatu bidang :)')

while True:                                                         #menggunakan while agar fungsi bisa diberhentikan
    header()
    jenisBid = input('Silakan memasukkan bidang yang ingin anda hitung (dalam huruf kapital) : ')
    if jenisBid == 'SEGITIGA':
        alas = float(input('Berapakah alasnya? (dalam cm) '))
        tinggi = float(input('Berapakah tingginya? (dalam cm) '))
        luas = luasSegitiga(alas, tinggi)
        print(F'Luas {jenisBid} adalah {luas}')
    elif jenisBid == 'LINGKARAN':
        jari_jari = float(input('Berapakah jari-jarinya? (dalam cm) '))
        luas = luasLingkaran(jari_jari)
        print(F'Luas {jenisBid} adalah {luas}')
    elif jenisBid == 'PERSEGI':
        sisi = float(input('Berapakah panjang sisinya? (dalam cm) '))
        luas = luasPersegi (sisi)
        print(F'Luas {jenisBid} adalah {luas}')
    elif jenisBid == 'PERSEGI PANJANG':
        lebar = float(input('Berapakah lebarnya? (dalam cm) '))
        panjang = float(input('Berapakah panjangnya? (dalam cm) '))
        luas = luasPersegiPanjang (panjang, lebar)
        print(F'Luas {jenisBid} adalah {luas}')  
    else:
        print('Mohon coba kembali, bidang yang anda input tidak tersedia untuk saat ini\n')
    lanjut = input('Apakah ingin menginput lagi? (y/n)')          #karena while tidak akan berhenti tanpa ada cancel,
    if lanjut == 'n':                                             #maka kita buatkan looping for untuk menyelesaikan input ketika input ingin diselesaikan
        break 
print('----Program Selesai Terimakasih----\n\n')


Selamat datang pada program sederhana mencari Luas suatu bidang :)
Silakan memasukkan bidang yang ingin anda hitung (dalam huruf kapital) : LINGKARAN
Berapakah jari-jarinya? (dalam cm) 1
Luas LINGKARAN adalah 3.14
Apakah ingin menginput lagi? (y/n)y
Selamat datang pada program sederhana mencari Luas suatu bidang :)
Silakan memasukkan bidang yang ingin anda hitung (dalam huruf kapital) : TRAPESIUM
Mohon coba kembali, bidang yang anda input tidak tersedia untuk saat ini

Apakah ingin menginput lagi? (y/n)n
----Program Selesai Terimakasih----




In [183]:
# Contoh Fungsi RETURN

import statistics    #mengimpor modul statistika

inputan = input('Masukkan deret bilangan (pisahkan dengan koma): ')
data = []    #menyiapkan data kosong sebagai tempat inputan

# konversi inputan ke dalam list yg berisi integer
for bilangan in inputan.split(','):    #diberikan split, karena inputan berisi tanda koma
    data.append(int(bilangan))         #mencari panjang/banyak data

rerata = statistics.mean(data)        #gunakan fungsi yang ada pada modul statistika
print(f'Data : {data}')               #memunculkan data terinput
print(f'Mean : {rerata}')             #memberi output berupak hasil rata-rata

Masukkan deret bilangan (pisahkan dengan koma): 1,2,3,4,5
Data : [1, 2, 3, 4, 5]
Mean : 3


In [ ]:
# Fungsi Return
def namaFungsi (argument):
    badan fungsi
    return output

In [168]:
# Contoh Fungsi
def kuadrat(input):
    outputKuadrat = input**2
    return outputKuadrat

y = kuadrat(3)
print(y)

9


In [190]:
# Contoh memunculkan deret Fibonacci
def fibonacci (n):
    if n < 1:
        return [n]

    listSebelumN = fibonacci(n - 1)
    angka1 = listSebelumN[-2] if len(listSebelumN) > 2 else 0
    angka2 = listSebelumN[-1] if len(listSebelumN) > 2 else 1 
    
    return listSebelumN + [angka1 + angka2]

panjang = int(input('Masukkan panjang deret:'))

# kita kurangin satu agar tidak kelebihan
print(fibonacci(panjang - 1))

Masukkan panjang deret:10
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


# 5.20 Numpy

In [209]:
#mengimpor numpy dan menggunakan nama alias np agar tidak ngetik kepanjangan
import numpy as np 

##### 5.20.1 Perintah Dasar pada Numpy

In [212]:
# membuat array dengan numpy
print('\nOutput array 1 dimensi : ')
a = np.array([0,1,2,3,4])
print(a)

print('\nOutput array 2 dimensi : ')
b = np.array([[5,6,7,8],[9,8,7,6]])
print(b)

print('\nOutput array 3 dimensi : ')
c = np.array([[[0,1,2,3],[4,5,6,7]],
              [[8,9,8,7],[6,5,4,3]],
              [[1,2,3,4],[5,6,7,8]]])
print(c)

#mengakses data array
print('\nOutput data array a dengan indeks 3 : ')
print(a[3])  #mengakses data pada array di numpy sama seperti list


Output array 1 dimensi : 
[0 1 2 3 4]

Output array 2 dimensi : 
[[5 6 7 8]
 [9 8 7 6]]

Output array 3 dimensi : 
[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]

Output data array a dengan indeks 3 : 
3


In [92]:
#ndim digunakan untuk mengecek dimensi pada array
b.ndim

2

In [207]:
#shape digunakan untuk mengecek dimensi, baris dan kolom suatu array
c.shape

(3, 2, 4)

##### 5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy

In [219]:
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #menginisialisasi variabel
print(d)                                         #mencetak array

print (d[0,3])       #indeks pada python selalu dimulai dari 0, maka ini mencetak elemen array d yg berada di baris 1 kolom 4
print(d[1,:])        #untuk mencetak semua elemen pada baris kedua 
print(d[:,2])        #untuk mencetak semua elemen pada kolom ketiga
print(d[0,0:3:2])    #untuk baris pertama, kolom pertama sampai kolom 3 dengan loncatan 2

d[0,0] = 100         #ketika ingin mengubah suatu elemen pada array
print(d)             #untuk mencetak perintah

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
4
[5 6 7 8]
[ 3  7 11]
[1 3]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


##### 5.20.3 Matrix pada Numpy

In [240]:
# Beberapa perintah dalam Numpy untuk membuat matrix

#np.ones((...,...))
#mencetak matriks dengan anggota 1, dengan baris dan kolom sesuai dengan yg diperintahkan
print('Output matriks anggota 1 dengan baris 2 dan kolom 3 : ')
print(np.ones((2,3)))    

print()

#np.zeros((...,...))
#mencetak matriks dengan anggota 0, dengan baris dan kolom sesuai dengan yg diperintahkan
print('Output matriks anggota 0 dengan baris 3 dan kolom 2 : ')
print(np.zeros((3,2))) 

print()

#np.identity((...,...))
#mencetak matriks identitas, dengan baris dan kolom sesuai dengan yg diperintahkan
print('Output matriks identitas 4 x 4 : ')
print(np.identity(4)) 

print()

#np.ones((...,...,...))
#mencetak matriks dengan anggota 1, dengan jumlah, baris dan kolom sesuai dengan yg diperintahkan
print('Output matriks anggota 1 dengan jumlah matriks 2, 3 baris dan 4 kolom : ')
print(np.ones((2,3,4)))    

print()

#np.full((...,...),...)
#mencetak matriks dengan anggota pada indeks ketiga, dengan jumlah, baris dan kolom sesuai dengan yg diperintahkan
print('Output matriks anggota 9 dengan 3 baris dan 2 kolom : ')
print(np.full((3,2),9))    

print()

#np.random.rand(...,...)
#mencetak matriks yang anggotanya acak 
print('Output matriks anggota random dengan 4 baris dan 3 kolom : ')
print(np.random.rand(4,3)) 

print()

#np.random.randint(...,..., size=(...,...))
#mencetak matriks yang anggotanya acak dengan tipe data integer acak dari ukuran yang diberikan
print('Output matriks anggota random integer 1-10 dengan 3 baris dan 4 kolom : ')
print(np.random.randint(1,10,size=(3,4)))  

Output matriks anggota 1 dengan baris 2 dan kolom 3 : 
[[1. 1. 1.]
 [1. 1. 1.]]

Output matriks anggota 0 dengan baris 3 dan kolom 2 : 
[[0. 0.]
 [0. 0.]
 [0. 0.]]

Output matriks identitas 4 x 4 : 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Output matriks anggota 1 dengan jumlah matriks 2, 3 baris dan 4 kolom : 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

Output matriks anggota 9 dengan 3 baris dan 2 kolom : 
[[9 9]
 [9 9]
 [9 9]]

Output matriks anggota random dengan 4 baris dan 3 kolom : 
[[0.00307041 0.57991713 0.312947  ]
 [0.446758   0.49173617 0.11790004]
 [0.60733415 0.42571899 0.48412442]
 [0.7055605  0.35400399 0.24398799]]

Output matriks anggota random integer 1-10 dengan 3 baris dan 4 kolom : 
[[5 5 1 3]
 [2 3 9 5]
 [5 6 6 1]]


In [ ]:
#Latihan membuat matrik ukuran 10 x 10 dengan menggunakan Numpy

a = np.zeros((10,10))       #membuat base matriks
print(a) 

b = np.identity(4)          #membuat base diagonal utama
print(b)

c = 9*b                     #mengganti diagonal dengan angka 9
print(c)

d = np.ones((8,8))          #membuat matriks 8 x 8 untuk bagian dalam matriks 10 x 10
e = np.identity(8)*8        #membuat matriks identitas pada materiks 8 x 8
f = d+e                     #menggabungkan hasil d dan e
print (f)

c[1:-1,1:-1] = f            #update c yaitu baris kedua sampai 9 menjadi f
print(c)

g = np.identity(6)*9        #membuat matriks identitas 6 x 6 dengan diagonal 9
c[2:-2,2:-2] = g            #update c yaitu baris ketiga sampai 8 menjadi g
print(c)

h = np.ones((4,4))*2        #membuat matriks 4 x 4 dengan elemen 2
i = np.identity(4)*7        #membuat identitas 4 x 4 dengan elemen 7
j = h+i                     #menggabungkan hasil h dan i
print(j)

c[3:-3,3:-3] = j            #update c yaitu baris keempat sampai 7 menjadi j

k = np.identity(2)*9        #membuat matriks identitas 2 x 2 dengan diagonal 9

c[4:-4,4:-4] = k            #update c yaitu baris kelima sampai 6 menjadi k
print(c)

##### 5.20.4 Copy pada Numpy

In [256]:
# Kasus yang tidak diinginkan
a = np.array([1,2,3,4,5])       #menginisialisasi array a
print(a)

b = a                           #array b sama dengan a
print(b)

b[0] = 10                       #mengubah array b dengan indeks 0 menjadi 10
print(b)

print (a)                       #karena a = b, maka output yg tercetak akan sama

[1 2 3 4 5]
[1 2 3 4 5]
[10  2  3  4  5]
[10  2  3  4  5]


In [258]:
c = np.array([1,2,3,4,5])     #menginisialisasi array a
print(c)

d = c.copy()                  #mengcopy array c ke d
print(d)

d[0] = 10                     #mengubah array d dengan indeks 0 menjadi 10
print(d)

print(c)                      #karena array c dicopy ke d, maka elemen pada array c tidak ikut berubah

[1 2 3 4 5]
[1 2 3 4 5]
[10  2  3  4  5]
[1 2 3 4 5]


##### 5.20.5 Operasi Matematika pada Numpy

In [267]:
#operasi skalar dengan matriks
print('Berikut matriks yang akan dioperasikan :')
a = np.array([1,2,3,4,5])       #menginisialisasi array a
print(a)
b = np.array([6,7,8,9,10])     #menginisialisasi array b      
print(b)

print('\nBerikut hasil dari penjumlahan matriks a dan b :')
print(a+b)

print('\nBerikut hasil dari pengurangan matriks a dan b:')
print(a-b)

print('\nBerikut hasil dari perkalian matriks a dan b:')
print(a*b)

print('\nBerikut hasil dari pembagian matriks a dan b:')
print(a/b)

print('\nBerikut hasil dari matriks b dipangkatkan a:')
print(b**a)

Berikut matriks yang akan dioperasikan :
[1 2 3 4 5]
[ 6  7  8  9 10]

Berikut hasil dari penjumlahan matriks a dan b :
[ 7  9 11 13 15]

Berikut hasil dari pengurangan matriks a dan b:
[-5 -5 -5 -5 -5]

Berikut hasil dari perkalian matriks a dan b:
[ 6 14 24 36 50]

Berikut hasil dari pembagian matriks a dan b:
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]

Berikut hasil dari matriks b dipangkatkan a:
[     6     49    512   6561 100000]


In [280]:
# Fungsi Trigonometri pada Numpy
#Numpy menyediakan fungsi sin(), cos() dan tan() yang mengambil nilai dalam radian dan menghasilkan nilai sin, cos, dan tan yang seharusnya.

#1 np.cos(a)   -> untuk mencari nilai cos masing-masing elemen pada a
#2 np.sin(a)   -> untuk mencari nilai sin masing-masing elemen pada a
#3 np.tan(a)   -> untuk mencari nilai tan masing-masing elemen pada a
#4 np.sinh(a)  -> untuk mencari nilai invers/hiperbolik sin masing-masing elemen pada a
#5 np.cosh(a)  -> untuk mencari nilai invers/hiperbolik cos masing-masing elemen pada a
#6 np.tanh(a)  -> untuk mencari nilai invers/hiperbolik tan masing-masing elemen pada a
#7 np.sqrt(a)  -> untuk mencari nilai akar kuadrat masing-masing elemen pada a

#Contoh 1 menemukan nilai sinus pi/2
p = np.sin(np.pi/2)
print(p)

#Contoh 2 menemukan nilai sinus untuk semua nilai di dataSudut
dataSudut = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

q = np.sin(dataSudut)

print(q)

#Contoh 3 mengubah semua nilai dalam array berikut menjadi radian
sudutDerajat = np.array([90, 180, 270, 360])

r = np.deg2rad(sudutDerajat)

print(r)

#Contoh 4 mengubah semua nilai dalam array berikut menjadi derajat
sudutRadian = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

s = np.rad2deg(sudutRadian)

print(s)

1.0
[1.         0.8660254  0.70710678 0.58778525]
[1.57079633 3.14159265 4.71238898 6.28318531]
[ 90. 180. 270. 360.]


##### 5.20.6 Perkalian Matrik pada Numpy

Pada contoh sebelumnya, perkalian matriks dilakukan dengan mengoperasikan elemen yang baris dan kolomnya sama. Hal ini tentunya akan memberikan hasil berbeda jika yang kita kehendaki adalah perkalian dua
matriks. Perkalian matrik pada Numpy dapat menggunakan perintah matmul. Perlu dijadikan perhatian tentang ukuran matrik yang akan dikalikan harus
sesuai dengan persyaratan. Misalnya matrik ukuran (1x2) dapat dikalikan dengan matrik ukuran (2x3).

In [289]:
print('Berikut matriks yang akan dioperasikan :')
print('a')
a = np.array([[1,2,3,4],[5,6,7,8]])          #menginisialisasi array a 2 x 4
print(a)
print('b')
b = np.array([[9,10,11,12],[13,14,15,16]])   #menginisialisasi array b 2 x 4
print(b)

#perkalian matriks a dan b tidak sesuai kaidah, karena memiliki ukuran yang tidak sesuai, output yang dihasilkan tentu tidak sesuai juga
print('\nBerikut hasil operasi perkalian matriks a dan b :')
c = a*b
print(c)        #namun, output yang dihasilkan tidak sesuai dengan kaidah perkalian 2 matriks
#output yang dikasilkan seperti perkalian skalar karena kedua matriks memiliki ukuran yang sama

#kita coba gunakan matmul
# d = np.matmul(a,b)
# print(t)

#outputnya yaitu 
#  ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, 
       # with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

Berikut matriks yang akan dioperasikan :
a
[[1 2 3 4]
 [5 6 7 8]]
b
[[ 9 10 11 12]
 [13 14 15 16]]

Berikut hasil operasi perkalian matriks a dan b :
[[  9  20  33  48]
 [ 65  84 105 128]]


In [294]:
#Contoh yang sesuai kaidah
print('Berikut matriks yang akan dioperasikan :')
print('a')
a = np.array([[1,2,3,4],[5,6,7,8]])          #menginisialisasi array a 2 x 4
print(a)
print('b')
e = np.array([[9,10],[11,12],[13,14],[15,16]])   #menginisialisasi array e 4 x 2
print(e)

print('\nBerikut hasil operasi perkalian matriks a dan e :')
f = np.matmul(a,e)
print(f)

# g = a*e
# print(g) 
#output error karena kedua matriks memiliki ukuran yang berbeda, sehingga perkalian skalar tidak terjadi

Berikut matriks yang akan dioperasikan :
a
[[1 2 3 4]
 [5 6 7 8]]
b
[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]

Berikut hasil operasi perkalian matriks a dan e :
[[130 140]
 [322 348]]


##### 5.20.7 min, max dan sum pada Numpy

In [315]:
#menginisialisasi array
print('Berikut adalah matriks a :')
a = np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])
print (a)

print('\nBerikut adalah nilai minimum elemen pada matriks a :')
b = np.min(a) 
print(b)

print('\nBerikut adalah nilai minimum elemen baris pada masing-masing baris matriks a :')
c = np.min(a, axis=1) 
print(c)

print('\nBerikut adalah nilai minimum elemen kolom pada masing-masing baris matriks a :')
d = np.min(a, axis=0) 
print(d)

print('\nBerikut adalah nilai maksimum elemen pada matriks a :')
e = np.max(a) 
print(e)

print('\nBerikut adalah nilai maksimum elemen baris pada masing-masing baris matriks a :')
f = np.max(a, axis=1) 
print(f)

print('\nBerikut adalah nilai maksimum elemen kolom pada masing-masing baris matriks a :')
g = np.max(a, axis=0) 
print(g)

print('\nBerikut adalah jumlah nilai semua elemen pada matriks a :')
h = np.sum(a)
print(h)          

print('\nBerikut adalah jumlah nilai elemen pada masing-masing baris matriks a :')
j=np.sum(a,axis=1)
print(j)

print('\nBerikut adalah jumlah nilai elemen pada masing-masing kolom matriks a :')
j = np.sum(a,axis=0)
print(j) 

Berikut adalah matriks a :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Berikut adalah nilai minimum elemen pada matriks a :
1

Berikut adalah nilai minimum elemen baris pada masing-masing baris matriks a :
[1 5 9]

Berikut adalah nilai minimum elemen kolom pada masing-masing baris matriks a :
[1 2 3 4]

Berikut adalah nilai maksimum elemen pada matriks a :
12

Berikut adalah nilai maksimum elemen baris pada masing-masing baris matriks a :
[ 4  8 12]

Berikut adalah nilai maksimum elemen kolom pada masing-masing baris matriks a :
[ 9 10 11 12]

Berikut adalah jumlah nilai semua elemen pada matriks a :
78

Berikut adalah jumlah nilai elemen pada masing-masing baris matriks a :
[10 26 42]

Berikut adalah jumlah nilai elemen pada masing-masing kolom matriks a :
[15 18 21 24]
