# 5.16 List 2 Dimensi

List 2 dimensi pada umumnya adalah menempatkan sebuah list di dalam list. List 2 Dimensi biasanya menyimpan data yang kompleks seperti maktriks.

In [31]:
matrix = [[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12],
          [13,14,15,16],]
print("Matriks yang kita miliki adalah :")
print (matrix)

# List 2 Dimensi terlihat seperti ada list di dalam list.
# INGAT!! Indeks selalu dimulai dari 0
#  - berarti dari matriks diatas terdapat kolom 0, kolom 1, sampai kolom 4
#  - dari matriks diatas terdapat baris 0, baris 1, sampai baris 4

#Cara menampilkan data pada List 2 Dimensi bisa menggunakan perulangan atau menunjukkan indeksnya

###### Menampilkan data dengan menunjukkan indeksnya ######
# Contoh, saya ingin mencetak data 12, data 12 terletak pada baris ketiga dan kolom keempat
# Karena indeks dimulai dari nol, maka data 12 terletak pada indeks 2 dan 3
# Kita bisa menampilkan dengan cara :
print("\nElemen yang terletak di baris ke-3 dan kolom ke-4 yaitu :")
print(matrix [2][3])

# Kita juga bisa membuatnya tanpa kata "PRINT"
# Kurung siku pertama menandakan indeks untuk baris dan kurung siku kedua menandakan indeks untuk kolom

# Contoh lain, saya ingin mencetak semua data yang ada pada baris keempat
# Karena indeks dimulai dari nol, maka baris keempat memiliki indeks 3
# Kita bisa menampilkan dengan cara :
print("\nElemen yang terletak di baris ke-4 yaitu :")
print(matrix [3])

# Kita juga bisa membuatnya tanpa kata "PRINT"
# Hanya terdapat 1 kurung siku yang menandakan indeks tersebut untuk baris

###### Menampilkan data dengan menunjukkan jangkauan indeksnya ######
# Contoh, saya ingin mencetak data baris kedua dan ketiga
# Karena indeks dimulai dari nol, maka baris jangkauan barisnya terletak pada 1-3 dengan indeks 3 tidak termasuk
# Kita bisa menampilkan dengan cara :
print("\nElemen yang terletak di baris ke-2 dan ke-3 yaitu :")
print(matrix [1:3])

Matriks yang kita miliki adalah :
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

Elemen yang terletak di baris ke-3 dan kolom ke-4 yaitu :
12

Elemen yang terletak di baris ke-4 yaitu :
[13, 14, 15, 16]

Elemen yang terletak di baris ke-2 dan ke-3 yaitu :
[[5, 6, 7, 8], [9, 10, 11, 12]]


In [45]:
###### Menampilkan data dengan perulangan menunjuk indeksnya ######
print("Berikut matriks yang memiliki jumlah digit karakter berbeda :")
for i in range(4):                       #perulangan pertama menunjukkan baris yaitu ada 4 baris
    for j in range (4):                  #perulangan kedua menunjukkan kolom yaitu ada 4 kolom
        print(matrix[i][j], end=' ')     #agar data yang tercetak terlihat seperti matriks, tambahkan (end=' ')
    print()                              #dan ketika perulangan j selesai, kita tambahkan enter dengan "print()"
    
#Saya masih belum tau caranya agar matriks ini terlihat lebih rapi, karena elemen-elemennya mengandung jumlah digit karakter yang berbeda
print()

#Contoh matriks lainnya
print("Berikut matriks yang memiliki 1 digit karakter :")
matriks1 =[[1,2,3,4],
          [2,4,6,8],
          [3,5,7,9]]
for i in range(3):                         #perulangan pertama menunjukkan baris yaitu ada 3 baris
    for j in range (3):                    #perulangan kedua menunjukkan kolom yaitu ada 3 kolom
        print(matriks1[i][j], end=' ')     #agar data yang tercetak terlihat seperti matriks, tambahkan (end=' ')
    print()                                #dan ketika perulangan j selesai, kita tambahkan enter dengan "print()"
    
print()
print("Berikut matriks yang memiliki 2 digit karakter :")
matriks2 =[[12,13],
          [14,15]]
for i in range(2):                         #perulangan pertama menunjukkan baris yaitu ada 2 baris
    for j in range (2):                    #perulangan kedua menunjukkan kolom yaitu ada 2 kolom
        print(matriks2[i][j], end=' ')     #agar data yang tercetak terlihat seperti matriks, tambahkan (end=' ')
    print()                                #dan ketika perulangan j selesai, kita tambahkan enter dengan "print()"
    
    

Berikut matriks yang memiliki jumlah digit karakter berbeda :
1 2 3 4 
5 6 7 8 
9 10 11 12 
13 14 15 16 

Berikut matriks yang memiliki 1 digit karakter :
1 2 3 
2 4 6 
3 5 7 

Berikut matriks yang memiliki 2 digit karakter :
12 13 
14 15 


In [54]:
###### Menampilkan data dengan perulangan tanpa menunjuk indeksnya ######
print("Berikut hasil matriks dengan perulangan tanpa menunjuk indeksnya :")
for i in matrix:               #kita akan mengakses data pada variabel matrix, i akan menunjukkan elemen pada setiap baris
    for j in i:                #j akan menunjukkan setiap elemen pada kolom
        print(j, end=' ')      #agar data yang tercetak terlihat seperti matriks, tambahkan (end=' ')
    print()                    #dan ketika perulangan j selesai, kita tambahkan enter dengan "print()"

print()

#Contoh lain
print("Berikut contoh lainnya :")
for i in matriks1:             #kita akan mengakses data pada variabel matrix, i akan menunjukkan elemen pada setiap baris
    for j in i:                #j akan menunjukkan setiap elemen pada kolom
        print(j, end=' ')      #agar data yang tercetak terlihat seperti matriks, tambahkan (end=' ')
    print()                    #dan ketika perulangan j selesai, kita tambahkan enter dengan "print()"

Berikut hasil matriks dengan perulangan tanpa menunjuk indeksnya :
1 2 3 4 
5 6 7 8 
9 10 11 12 
13 14 15 16 

Berikut contoh lainnya :
1 2 3 4 
2 4 6 8 
3 5 7 9 


In [7]:
for baris in matrix:
    print(baris)
    for kolom in baris:
        print(kolom)

[1, 2, 3, 4]
1
2
3
4
[5, 6, 7, 8]
5
6
7
8
[9, 10, 11, 12]
9
10
11
12
[13, 14, 15, 16]
13
14
15
16


# 5.17 Tuples

In [9]:
angka = (0,1,1,3,4,5)
print(angka[0])

0


# 5.18 Dictionaries

In [25]:
dataOrang={
    'nama' : 'Ketut Dogler',
    'umur' : 12,
    'apakah single?' : False
}

print(dataOrang['nama'])
# print(dataOrang['Nama'])

print('\n')
print(dataOrang.get('Nama'))
print(dataOrang.get('nama'))

Ketut Dogler


None
Ketut Dogler


In [31]:
print(dataOrang.get('tanggal-lahir'))
print(dataOrang.get('tanggal-lahir','2-2-2010'))
print(dataOrang)

print(dataOrang['tanggal-lahir']) #bersifat sementara

None
2-2-2010
{'nama': 'Ketut Dogler', 'umur': 12, 'apakah single?': False, 'HP': '0812345678'}


KeyError: 'tanggal-lahir'

In [29]:
dataOrang["HP"] = '0812345678'
print(dataOrang["HP"])
print(dataOrang)

0812345678
{'nama': 'Ketut Dogler', 'umur': 12, 'apakah single?': False, 'HP': '0812345678'}


In [32]:
angka = {
    '0' : 'nol',
    '1' : 'satu',
    '2' : 'dua',
    '3' : 'tiga',
    '4' : 'empat',
    '5' : 'lima',
    '6' : 'enam',
    '7' : 'tujuh',
    '8' : 'delapan',
    '9' : 'sembilan',
}

nomorHP = input("Masukkan nomor HP anda : ")
nomorAngka = ""
for isi in nomorHP:
    nomorAngka += angka.get(isi) + " "
print(nomorAngka)

Masukkan nomor HP anda : 085739846062
nol delapan lima tujuh tiga sembilan delapan empat enam nol enam dua 


In [34]:
angka = dict(
    0 =  'nol',
    1 = 'satu',
    2 = 'dua',
    3 = 'tiga',
    4 = 'empat',
    5 = 'lima',
    6 = 'enam',
    7 = 'tujuh',
    8 = 'delapan',
    9 = 'sembilan',
)

nomorHP = input("Masukkan nomor HP anda : ")
nomorAngka = ""
for isi in nomorHP:
    nomorAngka += angka.get(isi) + " "
print(nomorAngka)

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (2114928737.py, line 2)

# 5.19 Fungsi dalam Python

In [55]:
def fullName(firstName,lastName):
    print(f'Nama Lengkapnya adalah {firstName} {lastName}')

In [57]:
firstName = input("Nama depan anda adalah ")
lastName = input("Nama belakang anda adalah ")
fullName(firstName,lastName)

Nama depan anda adalah Putu
Nama belakang anda adalah Deswinta
Nama Lengkapnya adalah Putu Deswinta


In [61]:
def perkenalan(nama, asal):
  print(f"Perkenalkan saya {nama} dari {asal}")

nama = input('Siapa nama anda? ')
asal = input('Anda berasal dari mana? ')

perkenalan(nama, asal)
print("\n")

Siapa nama anda? Deswinta
Anda berasal dari mana? Denpasar
Perkenalkan saya Deswinta dari Denpasar




## 5.19.1 Tugas Fungsi pada Python

In [68]:
def waktuSampai(jarak,kecepatan):
    waktu = jarak/kecepatan
    print(waktu)
    
waktuSampai(80,60)

a = waktuSampai(80,60)
print(a)

1.3333333333333333
1.3333333333333333
None


In [69]:
def waktuTempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return waktu
    
waktuTempuh(80,60)

b = waktuTempuh(80,60)
print(b)

1.3333333333333333


# 5.20 Numpy

In [73]:
import numpy as np

In [74]:
a = np.array([0,1,2,3,4])
print(a)

[0 1 2 3 4]


In [79]:
b = np.array([[5,6,7,8],[9,8,7,6]])
print(b)

[[5 6 7 8]
 [9 8 7 6]]


In [94]:
c = np.array([[[0,1,2,3],[4,5,6,7]],
              [[8,9,8,7],[6,5,4,3]],
              [[1,2,3,4],[5,6,7,8]]])
print(c)

[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [92]:
b.ndim

2

In [95]:
c.ndim

3

In [96]:
c.shape

(3, 2, 4)